# fly.toml app configuration file generated for ml-serving-api-titanic-u2 on 2023-08-08T12:04:56+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ml-serving-api-titanic-u2"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ["app"]
